import * as Joi from 'joi';
export const validationSchema = Joi.object({
    DATABASE_URL: Joi.string().required(),
    JWT_ACCESS_SECRET: Joi.string().min(16).required(),
    JWT_REFRESH_SECRET: Joi.string().min(16).required(),
    CORS_ORIGIN: Joi.string().optional(),
    NODE_ENV: Joi.string()
        .valid('development', 'production', 'test')
        .default('development'),
    PORT: Joi.number().default(3000),
    OTP_LENGTH: Joi.number().valid(6, 8).default(8),
    EMAIL_FROM: Joi.string().required(),
    RESEND_API_KEY: Joi.string().optional(),
    STOCK_THRESHOLD_CRON: Joi.string().default('0 7 * * *'),
    QUEUE_WAIT_CHECK_CRON: Joi.string().default('*/30 * * * *'),
    QUEUE_WAIT_THRESHOLD_HOURS: Joi.number().default(5),
    PRESCRIPTION_CYCLE_CHECK_CRON: Joi.string().default('0 0 * * *'),
    EXPIRATION_CHECK_CRON: Joi.string().default('0 8 * * *'),
    EXPIRATION_WARNING_DAYS: Joi.number().default(6),
    FIREBASE_PROJECT_ID: Joi.string().required(),
    FIREBASE_CLIENT_EMAIL: Joi.string().required(),
    FIREBASE_PRIVATE_KEY: Joi.string().required(),
    CLOUDINARY_CLOUD_NAME: Joi.string().required(),
    CLOUDINARY_API_KEY: Joi.string().required(),
    CLOUDINARY_API_SECRET: Joi.string().required(),
    CLOUDINARY_AUTH_TOKEN_KEY: Joi.string().optional().allow(''),
    PURCHASE_RECEIPT_MAX_IMAGES: Joi.number().min(1).max(30).default(10),
    CHATBOT_INTERNAL_SECRET: Joi.string().min(32).required(),
    CHATBOT_SERVICE_URL: Joi.string().uri().required(),
    DISPOSAL_SALE_MAX_IMAGES: Joi.number().min(1).max(30).default(10),
});
